use_frameworks!

target 'LGActivityModule_Example' do
  pod 'LGActivityModule', :path => '../'

  target 'LGActivityModule_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
